---
language: python
python: "2.7"

# whitelist
branches:
  only:
    - master
    - develop

# used to test against multiple versions of ansible
env:
  - ANSIBLE_VERSION=1.6
  # - ANSIBLE_VERSION=1.7
  # - ANSIBLE_VERSION=1.8
  - ANSIBLE_VERSION=1.9

before_install:
  # update ubuntu packages
  - sudo apt-get update -qq

install:
  - pip install -q ansible==$ANSIBLE_VERSION

before_script:
  # remove nvm file
  - sudo rm -r ~/.nvm

script:
  # create an inventory list
  - echo localhost > inventory
  # perform a syntax check on the playbook, but do not execute it
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  # run role/playbook to check if ansible script works
  - ansible-playbook -i tests/inventory tests/test.yml -c local --sudo
  # run the role/playbook again, testing idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml -c local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
    
after_script:
  # test if nvm has been installed by ansible playbook
  - source ~/.bashrc && nvm --version
  
