---
  
- name: Install Required Packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items: required_packages

- include: nvm.yml

- include: node.yml

- include: pkgs.yml
  when: "{{ nvm_npm_pkgs | length }} > 0"
